apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: parasol-insurance-listener
  namespace: ${{ values.namespace }}
spec:
  host: el-${{ values.owner }}-${{ values.branch }}.${{ values.cluster_subdomain }}
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-parasol-insurance-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
