kind: Secret
apiVersion: v1
metadata:
  name: parasol-db
  namespace: ${{ values.namespace }}
  labels:
    app.kubernetes.io/name: parasol-insurance-${{ values.owner }}
    app.kubernetes.io/part-of: parasol-insurance-dev
stringData:
  database-user: parasol
  database-password: parasol
  database-name: parasol
type: Opaque
