apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: parasol-insurance-dev-${{ values.owner }}
  title: Parasol Insurance Dev (${{ values.branch }})
  description: Development sandbox for Parasol Insurance (${{ values.branch }} branch)
  annotations:
    argocd/app-name: parasol-insurance-dev-${{ values.owner }}
    backstage.io/source-location: url:https://${{ values.gitlab_host }}/${{ values.owner }}/parasol-insurance/-/tree/${{ values.branch }}
    backstage.io/kubernetes-id: parasol-insurance-${{ values.owner }}-${{ values.branch }}
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/name=parasol-insurance-${{ values.owner }}-${{ values.branch }}"
    janus-idp.io/tekton: parasol-insurance
    gitlab.com/project-slug: ${{ values.owner }}/parasol-insurance
    sonarqube.org/project-key: parasol-insurance-${{ values.owner }}
  links:
    - url: https://devspaces.${{ values.cluster_subdomain }}/#https://${{ values.gitlab_host }}/${{ values.owner }}/parasol-insurance/-/tree/${{ values.branch }}
      title: Open in Dev Spaces
      icon: catalog
      type: devspaces
spec:
  type: service
  lifecycle: development
  owner: user:default/${{ values.owner }}
  system: parasol-insurance
